laravel/reverb

src/Servers/Reverb/Console/Commands/StartServer.php

https://github.com/laravel/reverb/assets/81873266/6c7e2451-2320-4a89-863f-ad7e59994fdd
Fix: #65 
Fix: #74
**Description**
This PR enhances the signal handling mechanism to support both Unix-like systems and Windows. It introduces support for SIGTSTP on Unix-like systems and implements Windows-specific signal handling using sapi_windows_set_ctrl_handler. This update improves the platform compatibility of the application and ensures proper signal handling across different operating systems
**Changes Made**
- Added SIGTSTP to the list of subscribed signals for Unix-like systems to not suspend process without gracefullyDisconnect the opened server
- Introduced a new method `handleSignalWindows() `to handle signals on Windows.
- Implemented Windows-specific signal handling using …

Fix: Update Signal Handling for Unix-like and added Windows Systems support

---

src/Console/Commands/InstallCommand.php

This PR updates the install process to:
- Always attempt to enable the `BroadcastServiceProvider` in `app.php`
- Always attempt to add Reverb's configuration options to `broadcasting.php`.
Resolves #79

[1.x] Fixes install command for applications migrated from 10.x to 11.x

---

src/Protocols/Pusher/Channels/Concerns/InteractsWithPrivateChannels.php
tests/Feature/Protocols/Pusher/Reverb/ServerTest.php
tests/Unit/Protocols/Pusher/Channels/PrivateChannelTest.php

Resolves #89 
Updated the `verify` method for private channels to accept a nullable auth token. Doing so means the `ConnectionUnauthorized` exception will be thrown and the correct error message sent across the WebSocket rather than throwing a `TypeError` and stopping the server.

[1.x] Prevents exception when no auth token passed

---

src/Protocols/Pusher/Channels/Concerns/InteractsWithPresenceChannels.php

- https://github.com/laravel/reverb/issues/92
Using `collection->values()->all()` instead of `collection->all()` to reset the array key.
|Before|After|
|-|-|
|![](https://github.com/laravel/reverb/assets/11713395/e4513de1-08c0-456c-b148-5b3d8a42eb9b)|![](https://github.com/laravel/reverb/assets/11713395/64030ece-8d23-4930-af48-38f3fb0e8f4c)|

Fix invalid response data of event pusher_internal:subscription_succeeded

---

config/reverb.php
src/Servers/Reverb/Factory.php
tests/Unit/Servers/Reverb/FactoryTest.php

See: https://github.com/laravel/reverb/issues/78

[1.x] Fix the issue for connecting if the SSL is not verified peer

---

src/Loggers/CliLogger.php
src/Protocols/Pusher/Channels/Channel.php
src/Protocols/Pusher/Channels/Concerns/InteractsWithPresenceChannels.php
src/Protocols/Pusher/Http/Controllers/EventsBatchController.php
src/Protocols/Pusher/Http/Controllers/EventsController.php
src/Protocols/Pusher/PusherPubSubIncomingMessageHandler.php
src/Protocols/Pusher/Server.php
src/Servers/Reverb/Http/Server.php
src/Servers/Reverb/Publishing/RedisPubSubProvider.php
tests/Feature/Protocols/Pusher/Reverb/EventsBatchControllerTest.php
tests/Feature/Protocols/Pusher/Reverb/EventsControllerTest.php
tests/ReverbTestCase.php

This PR improves the exception handling and logging capabilities of Reverb by:
1. Using the `JSON_THROW_ON_ERROR` flag when decoding payloads
2. Logging exceptions before closing the connection with a 500 to provide visibility of the cause of the issue
3. Logging broadcast messages
This PR replaces #119

[1.x] Improves exception handling and logging

---

src/Protocols/Pusher/Http/Controllers/EventsController.php
tests/Feature/Protocols/Pusher/Reverb/EventsControllerTest.php
tests/TestConnection.php

Probably will fix issue with the Exception when use toOthers()
Resolves #121

[1.x] Allows for disconnections when broadcasting to others

---

src/Protocols/Pusher/EventHandler.php
tests/Feature/Protocols/Pusher/Reverb/ServerTest.php
tests/Unit/Protocols/Pusher/EventTest.php
tests/Unit/Protocols/Pusher/ServerTest.php

This PR fixes missing `data` property for `pusher_internal` events.
Fixes #123

[1.x] Sends data property when empty

---

src/Protocols/Pusher/Channels/Concerns/InteractsWithPrivateChannels.php
src/Protocols/Pusher/Http/Controllers/Controller.php
tests/FakeConnection.php
tests/Feature/Protocols/Pusher/Reverb/ServerTest.php
tests/ReverbTestCase.php

Fix general spelling errors on project

[1.x] Fix spelling errors

---

src/Servers/Reverb/Publishing/RedisPubSubProvider.php

When using secure Redis connections with TLS, Reverb will only construct a TCP connection and could not re-use the existing TLS connection.
`rediss://` is the secure scheme when using TLS (See: https://www.iana.org/assignments/uri-schemes/prov/redis and also [`clue/reactphp-redis` repository](https://github.com/clue/reactphp-redis?#__construct))
This PR checks if the Redis connection has a `scheme` option with `tls` as value (as per Laravel's documentation) and add's the `s` to the connection URL.
**PS**: the `$protocol` variable name might not be the best choice so I'm open for suggestions on that.

Use secure redis connection if config is set to use TLS

---

src/Protocols/Pusher/Http/Controllers/Controller.php
src/Servers/Reverb/Http/Server.php
tests/Feature/Protocols/Pusher/Reverb/EventsControllerTest.php

This PR resolved #142 
We were catching an exception, but not stopping execution of the code which could result in a message being delivered when sent with an invalid app ID.
This could only really happen if you updated the App ID in your environment and immediately began broadcasting with the new App ID without restarting the Reverb server.
To address this, the exception is being caught higher up by the server instead of directly in the controller.

[1.x] Handles stale app IDs

---

src/Protocols/Pusher/Http/Controllers/PusherController.php

I installed and setup Reverb (Laravel 11, PHP 8.3) and have been getting the same type error from the beginning when running the server:
```
Laravel\Reverb\Protocols\Pusher\Http\Controllers\PusherController::Laravel\Reverb\Protocols\Pusher\Http\Controllers\{closure}(): Argument #1 ($message) must be of type string, Ratchet\RFC6455\Messaging\Message given, called in .../app/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php on line 254
```
Not sure why nobody else seems to be getting this error, but maybe something to do with strict typing as `Ratchet\RFC6455\Messaging\Message` is a stringable object. Anyways, just coercing `$message` to a string resolved the issue for me and I was getting successful pings after that.
All tests are still passing.

Fixed type error in connection message handler

---

src/Protocols/Pusher/Contracts/ChannelManager.php
src/Protocols/Pusher/Managers/ArrayChannelManager.php
tests/Unit/Protocols/Pusher/Managers/ChannelManagerTest.php

I came across a situation in my project that needs to check if a channel exists or not.
We can utilize  `find()` method and check if the result is null or not; But since Reverb aims for performance, better to only check if key exists or not instead of loading object. It also gives freedom if someone wants to bind it's own `DbChannelManager` driver instead of `array`.

[1.x] Adds exists() method to ChannelManager

---

config/reverb.php
phpstan.neon.dist
src/Servers/Reverb/Console/Commands/StartServer.php

This PR resolves #148 
Telescope works by stroing events after a response has been sent or a job processed. With Reverb, neither of these things happen so Telescope entries accumulate causing in memory consumption.
This PR attempts to address that by periodically storing and flushing the buffer of entries in a similar approach to Pulse.

[1.x] Handles Telescope ingest

---

src/Servers/Reverb/Factory.php

When used with secure sites on Valet or Herd, Reverb will automatically discover the certificate and use it to enable secure WebSocket connections.
This works nicely, but there are issues in Chrome.
If you use Echo to connect over wss, Chrome will reject the connection without any useful reason why.
What's even more strange is if you navigate to https://site.test:8080 in the browser, Reverb will load the page with no SSL error.
After doing so, attempting to connect via Echo again (wss://site.test:8080), results in a successful connection 🤷
I was able to go deep into Chrome and review the logs which exposed an error: `ERR_SSL_CLIENT_AUTH_CERT_NEEDED`
This indicates an issue in the SSL handshake between client and server. The server doesn't trust the certificate being used by the client - …

[1.x] Fixes SSL connection issues in Chrome / Arc

---

src/Servers/Reverb/Console/Commands/StartServer.php

It was pointed out to me that it's recommended in the docs to have Telescope installed, but toggle the service provider depending on the environment.
This means although `\Laravel\Telescope\Telescope::class` is available in the project, `\Laravel\Telescope\Contracts\EntriesRepository::class` is not bound.
This PR updates the check for the bound class instead.

[1.x] Improves check for Telescope

---

config/reverb.php
src/Servers/Reverb/Publishing/RedisPubSubProvider.php
src/Servers/Reverb/ReverbServerProvider.php

This adds a configuration setting and check to allow Redis in cluster mode (see issue #160). Adding `REVERB_SCALING_CLUSTER_ENABLED=true` to the `.env` file will change the config used from `database.redis.default` to `database.redis.clusters.default.0`. Like the horizontal scaling feature, this is off by default.

Add configuration for Redis cluster support

---

src/Protocols/Pusher/Http/Controllers/ChannelController.php

Currently calling `getChannelInfo()` without `info` will lead to "500 Internal Server Error" with the error message `[ERROR] Undefined array key "info"`. The PR fixes this.

Fix accessing potentially undefined array key

---

src/Servers/Reverb/Http/Response.php

The header function inside the JsonResponse class expects array|null|string and previously we were passing an integer.
I see little reason in not sticking to the variable types defined in the json response's set function.
Pedantic change but strict types can now be used

Cast content length to string when setting headers in HTTP Response.php

---

src/Servers/Reverb/Http/Request.php

Content-Length should be compared to the length of the request body otherwise `bufferLength()` includes the length of the headers and body

Compare content-length to the length of the request body

---

src/Protocols/Pusher/Http/Controllers/HealthCheckController.php
src/Servers/Reverb/Factory.php
tests/Feature/Protocols/Pusher/Reverb/HealthCheckControllerTest.php
tests/ReverbTestCase.php

New `/health_check` endpoint will be available when Reverb server is running, that will response with `{"health":"OK"}` to support k8s HTTP health checks required by some cloud provider Load Balancers (i.e. GCP)

Add health check endpoint (laravel#190)

---

composer.json
src/Servers/Reverb/Console/Commands/StartServer.php
src/Servers/Reverb/Http/Server.php

ReactPHP runs in one thread and can't be interrupted. So, when we have some blocking stuff inside one of the handlers, for example connection to Redis not stable, or turn on xDebug make garbage collector slower than usual, the whole loop is blocked, and all other handlers will be delayed!

[1.x] Prevents blocking event loop

---

src/Application.php
src/ConfigApplicationProvider.php
src/Pulse/Recorders/ReverbConnections.php
tests/FakeApplicationProvider.php
tests/Unit/ProviderTest.php

This PR updates how the connections recorder for Pulse retrieves applications. It now retrieves them from the registered ApplicationProvider. This extends the Application constructor with the options array.
Currently, the connections recorder does not work with providers other than the config provider. Another potential provider could be a database provider.
Let me know if you are willing to accept this kind of PR. I am happy to add test cases for this or update the PR.

[1.x] Retrieves applications from provider in Pulse connections recorder

---

composer.json
src/Servers/Reverb/Console/Commands/StartServer.php
src/Servers/Reverb/Http/Server.php

Wrapping a callback function with `async()` only makes sense when combined with `await()` or we want to return a promise. `gc_collect_cycles()` is a blocking function and wrapping `async()` does not make it non-blocking.
See: https://github.com/laravel/reverb/pull/195#issuecomment-2132613234

Revert #195

---

src/Protocols/Pusher/Channels/Concerns/InteractsWithPresenceChannels.php
tests/Feature/Protocols/Pusher/Reverb/ServerTest.php
tests/Unit/Protocols/Pusher/Channels/PresenceChannelTest.php

This PR resolves #213 
The fixes introduced all occur when a user is logged in to a single account, but connected to Reverb in multiple tabs or browswers.
The `subscription_succeeded` event should contain a unique list of connected user IDs.
The `member_added` event should only be dispatched the first time a user connects to the channel (e.g. the first browser tab).
The `member_removed` event should only be dispatched when the user no longer has any connections remaining (e.g. closed all tabs).
Details can be found in the [Pusher spec](https://pusher.com/docs/channels/using_channels/presence-channels/#pushermember_added-1661816671).

[1.x] Correctly dispatches presence events

---

src/Protocols/Pusher/Server.php
tests/FakeConnection.php
tests/Unit/Protocols/Pusher/ServerTest.php

At present the allowed origins option does not allow for wildcard origins other than `['*']`. As such, if you want to support a set of subdomains as well as the primary domain, you have to list out each one individually into the `reverb.php` config file, e.g.,:
```php
...
'allowed_origins' => ['laravel.com', 'www.laravel.com', 'subdomain.laravel.com'],
...
```
This is all fair and well if the subdomains are well defined, but if you either have a lot of them or your application allows the users to define a subdomain e.g., in the context of a multi-tenant setup, then you may not be able to define these easily.
However, the only wildcard support available is the `['*']` option, but this opens it to all origins, which may not be desired.
This pull request would provide support for wildcard …

[1.x] Add support for wildcard allowed origins

---

src/Protocols/Pusher/Server.php

A message like:
```
1▕ { 
2▕     "event": "pusher:ping", 
3▕     "data": "" 
4▕ } 
```
results in `TypeError`:
```
Laravel\Reverb\Protocols\Pusher\EventHandler::handle(): Argument #3 ($payload) must be of type array, string given, called in /var/www/html/api/vendor/laravel/reverb/src/Protocols/Pusher/Server.php on line 56
```
which takes the server down.
This fixes it.

Prevent message with data: "" taking server down

---

src/Events/ChannelCreated.php
src/Events/ChannelRemoved.php
src/Protocols/Pusher/Managers/ArrayChannelManager.php

When channel is going to be created or removed an event will be triggered, this may be useful when subscriptions are managed by https://github.com/nuwave/lighthouse and channel should be removed from cache when user leaves (removed) form it

Dispatch an event when channel created or removed.

---

composer.json

Laravel Prompts 0.2.0 was released last week: https://github.com/laravel/prompts/releases/tag/v0.2.0

[1.x] Supports `laravel/prompts` v0.2

---

src/Connection.php
src/Contracts/Connection.php
src/Protocols/Pusher/EventHandler.php
src/Protocols/Pusher/Http/Controllers/PusherController.php
src/Protocols/Pusher/Server.php
src/Servers/Reverb/Connection.php
tests/FakeConnection.php
tests/Feature/Protocols/Pusher/Reverb/ServerTest.php
tests/TestConnection.php

This PR attempts to resolve #224 
It's been reported that some of the Pusher clients don't support the `pusher:ping|pong` event format for handling pings and pongs and will, instead, rely on the low-level ping/pong control frames provided by the WebSocket specification.
This PR aims to address that by:
- Defaulting to Pusher's `pusher:ping|pong`
- Updating the last active timestamp on the connection when receiving a low-level `ping` control frame. The aim here is to prevent connections getting pruned by the `PruneStaleConnections` job
- Set a boolean status on the connection of `usesControlFrames` when receiving a low-level `ping` control frame and, when this value is `true`, send low-level `ping` control frames when running the `PingInactiveConnections` job.

[1.x] Optionally uses control frames for handling ping and pong

---

src/Protocols/Pusher/EventDispatcher.php
src/Protocols/Pusher/PusherPubSubIncomingMessageHandler.php
tests/Feature/Protocols/Pusher/Reverb/EventsControllerTest.php
tests/Unit/EventTest.php

Pass SocketID through redis, and filter it on the receiving end.
This ensures that ->toOthers() works with scaling = true

[1.x] Allow publishing to others only when using Redis

---

src/Protocols/Pusher/EventDispatcher.php

My fix for scaling with redis in PR 275 faails with an exception if a queue worker creates a push message, as the validate_socket() method does not accept null, but activates if the socket_id key is present.
I changed the code, so that the socket_id key is only is only set, if it is non-null.

Bugfix for PR 275 - omit socket-id if null

---

src/Protocols/Pusher/Managers/ArrayChannelManager.php
tests/Unit/Protocols/Pusher/EventTest.php

Fixes issue https://github.com/laravel/reverb/issues/291

[1.x] Check if channel variable isn't null when passed as a filter on channels() method in ArrayChannelManager

---

config/reverb.php
src/Servers/Reverb/Console/Commands/StartServer.php
src/Servers/Reverb/Factory.php
tests/Feature/Protocols/Pusher/Reverb/ServerTest.php
tests/ReverbTestCase.php

I like having a single domain name to run an application. This allows the server to add a path prefix to all server routes, which will allow it to run at a subpath of an application. This allows for the following (relevant snippets) configuration in an app:
```env
REVERB_SERVER_PATH="/ws"
REVERB_PATH="/ws"
VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
VITE_REVERB_HOST="${REVERB_HOST}"
VITE_REVERB_PORT="${REVERB_PORT}"
VITE_REVERB_SCHEME="${REVERB_SCHEME}"
VITE_REVERB_PATH="${REVERB_PATH}"
```
```php
// config/broadcasting.php
'connections' => [
'reverb' => [
'driver' => 'reverb',
'key' => env('REVERB_APP_KEY'),
'secret' => env('REVERB_APP_SECRET'),
'app_id' => env('REVERB_APP_ID'),
'options' => [
'host' => env('REVERB_HOST'),
'port' => env('REVERB_PORT', 443),
'scheme' => env('REVERB_SCHEME', …
```

[1.x] Adds support for server path prefix

---

src/Protocols/Pusher/ClientEvent.php
tests/Unit/Protocols/Pusher/ServerTest.php

This PR allow client event without data. Added tests to tests/Unit/Protocols/Pusher/ServerTest.php.
- ✅ Ability to send events without data
None.
Fixes #314.

Allow client event without data

---

composer.json
src/Servers/Reverb/Http/Router.php

[1.x] Bump dependencies to fix tests

---

src/Servers/Reverb/Http/Router.php
tests/Feature/Protocols/Pusher/Reverb/ServerTest.php

Sets the `X-Powered-By` response header for the initial connection to "Laravel Reverb"
**Current**
**Updated**

[1.x] Sets X-Powered-By header

---

src/Console/Commands/InstallCommand.php

Fixes #309 by matching one or more of any character (rather than word, digit or whitespace only) after `BROADCAST_DRIVER=` or `BROADCAST_CONNECTION=` in the `.env` during the `reverb:install` command.

[1.x] Fix issue with quoted string in .env when running install command

---

src/Protocols/Pusher/Channels/Concerns/InteractsWithPresenceChannels.php
tests/Feature/Protocols/Pusher/Reverb/ServerTest.php
tests/Unit/Protocols/Pusher/Channels/PresenceCacheChannelTest.php
tests/Unit/Protocols/Pusher/Channels/PresenceChannelTest.php

**Background**
Previously, the `data` field in presence channel events (`member_added`, `member_removed`) was sent as an object, not as a JSON-encoded string per the Pusher protocol. This caused client compatibility issues.
* [Pusher protocol for `member_added`](https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol/#pusher_internalmember_added-pusher-channels-greater-client)
* [Pusher protocol for `member_removed`](https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol/#pusher_internalmember_removed-pusher-channels-greater-client)
**What was fixed**
* Now, the `data` field is always a JSON-encoded string, as required by Pusher.
* Updated related tests to expect the correct format.
* Ensured empty data is sent as `'{}'`.

Fix encoding of data field in presence channel events to match Pusher protocol

---

config/reverb.php
src/Application.php
src/ConfigApplicationProvider.php
src/Protocols/Pusher/Exceptions/ConnectionLimitExceeded.php
src/Protocols/Pusher/Server.php
tests/FakeApplicationProvider.php
tests/Feature/Protocols/Pusher/Reverb/ServerTest.php
tests/ReverbTestCase.php
tests/Unit/Protocols/Pusher/ServerTest.php

This PR adds support for connection limits for those users who wish to limit the number of active connections to a given application as [supported by the Pusher protocol](https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol/#4000-4099).
This is opt-in functionality to preserve backward compatibility.

[1.x] Adds optional application level connection limits
